const answers = {
    2: "Enquiry - Booking Details/ Partner Details",
    3: "NEDD TO CONFIRM ORALLY",
    4: "A surge charge refers to an additional fee or higher pricing applied to a product or service during periods of high demand or limited availability.",
    5: "Changes in Order Requirement - Location Changes",
    6: "Cancellation - PNM Order",
    7: "Changes in Order Requirement - Location Changes",
    8: "Delay",
    9: "Changes in Order Requirement - Reschedule/ Change Date & Time",
    10: "Inform the customer that its from one state to another state so u need to pay 80% amount in pickup location and 20% amount in drop location",
    11: "Vendor Rejects the Order",
    12: "Vendor Rejects the Order",
    13: "Supervisor Reject Order - PNM",
    14: "Service Related - Not Enough Packing Materials",
    15: "Unable to find Customer's Location (Pickup/Drop)",
    16: "Customer/Partner/Supervisor Unreachable",
    17: "Changes in Order Requirement - Changes in Materials/ Extra Items",
    18: "Service Related - Wrong vehicle assigned",
    19: "Service Related - Wrong vehicle assigned",
    20: "Changes in Order Requirement - Heavy/ Oversize Items - PNM",
    21: "NO ZING ( CONNECT CONCALL WITH PARTNER AND EDUCATE HIM THAT CUSTOMER WILL NOT GIVE ANY FUEL CHARGES HE AS TO ARRANGE BY HIS OWN )",
    22: "Service Related - Behavior/Hygeine Issues",
    23: "Service Related - Behavior/Hygeine Issues",
    24: "Cancellation - PNM Order",
    25: "Changes in Order Requirement - Floor Change",
    26: "Sir in case if u wants to keep the carton boxes after shifting means u need to pay 60 rs per box",
    27: "kindly inform to customer in case if customer wants to keep the carton boxes after shifting means customer need to pay 60 rs per box",
    28: "Payment Related - Partner/Supervisor requesting for cash payment",
    29: "NO ZING ( CONNECT CONCALL WITH CUSTOMER AND WE WILL INFORM THE CUSTOMER THAT DUE TO NO ENTRY THERE WILL BE DELAY IN DELIVERY OF GOODS )",
    30: "NA",
    31: "First confirm the order details than make conference call to customer and check whether customer added any amount in wallet and check if he wants to pay through wallet if yes means keep ticket open with clear comments",
    32: "Payment Related - Changes in Invoice/ Add GST details",
    33: "Service Related - Goods Damage / Missing / Stolen / Good Left in Vehicle",
    34: "Sorry for inconviaance sir in LBR order we cannot provide packing service so if u want packing service means u can choose packers and movers option sir",
    35: "Enquiry - Feedback link not received",
    36: "Payment Related - Customer is refusing to pay/ Underpayment",
    37: "Cancellation - PNM Order",
    38: "union",
    39: "Customer/Partner/Supervisor Unreachable",
    40: "Supervisor Reject Order - PNM",
    41: "Supervisor Reject Order - PNM",
    42: "Service Related - Wrong vehicle assigned",
    43: "Sir in LBR order u will get 1 Vehicle, 1 labor and driver (Driver will act as helper). and 7 feet vehicle will come to location sir and u can load upto 750 kgs overall but one materials should be less than 50 kgs sir",
    44: "Iam extreemly sorry for the inconvince that is rope pulling will not be provided in drop location in PTL orders sir it is only provided in pickup location",
    45: "customer that we cannot provide specific charges for this service. If they wish to avail of this service, they can add it, and standard charges will be included in the total amount.",
    46: "DELAY - PNM",
    47: "Require Add-on Services",
    48: "Changes in Order Requirement - Parking to Lift Distance",
    49: "LBR orders with Order Source: PORTER_ASSIST – Toll charges are included in the quotation. connect con call the partner and inform the same no need to collect toll amount customer side.\nLBR orders with Order Source: CUSTOMER – Toll charges are not included in the quotation and must be paid separately by the customer.",
    50: "cancellation LBR",
    51: "discount",
    52: "amount",
    53: "Service Related - Goods Damage / Missing / Stolen / Good Left in Vehicle completed order stage direct open ticket",
    54: "Service Related - Goods Damage / Missing / Stolen / Good Left in Vehicle",
    55: "Changes in Order Requirement - Require Add-on Services",
    56: "Changes in Order Requirement - Require Add-on Services",
    57: "Sir sorry for inconvenance plants, Filled gas cylinders (LPG),Flammable Items and big glass materials are non-shiftable items.",
    58: "Cancellation - PNM Order IN THAT SELECT THE REASON EXYRA MATERIAL ON SAME QUOTATION",
    59: "Payment Related - Tip Collected",
    60: "Changes in Order Requirement - Add-on",
    61: "Changes in Order Requirement - Lift Status Change",
    62: "(ENQUIRY NOR ) partner that as per the availability you will receive the order.",
    63: "NEED TO CHECK IN ORDER DETAILS IF NO WAYPOINT ADDED MEANS U CAN INFORM THAT NO WAYPOINT IS ADDED HENCE UR NOT ABLE TO SEE ANY WAYPOINT IN UR APPLICATION",
    64: "iam extreemy sorry for inconviance sir as of now cancellation will be done from customer care end only and no option available in porter appliction",
    65: "iam extreemy sorry for inconviance sir we have stopped this service of pre shifting carton delivery boxes . On the shifting day our partner will bring the carton boxes with them",
    66: "All items such as furniture, kitchen items, etc., will be packed by Multi-layer packing.",
    67: "Sorry for inconviaance sir in LBR order we cannot provide packing service so if u want packing service means u can choose packers and movers option sir",
    68: "Cancellation - LBR https://zingtree.com/preview/982283122?tree_id=982283122&is_preview=1#3",
    69: "Supervisor Reject Order - PNM",
    70: "Supervisor Reject Order - PNM",
    71: "Iam extreemly sorry for incoviance sir when ur placing the order at that time only we can apply the discount code but after placing the order we cannot apply it",
    72: "Sir as per service u will get 2 options 1 singal layer and another multy layer so u can choose multi layer packing for electronic and fragile goods",
    73: "Payment Related - Partner asking for more money/ Extra amount collected u can inform the customer that only installation and un installation will be given in the service sir if there is required any extra materials like pipe, gas filling, wires etc means u need to pay extra sir to partner",
    74: "Sir iam extreemly sorry for inconviance as of now we are not providing any insurance to the goods which are transporting",
    75: "The \"default\" package will display the base price and include certain services ( Single-layer packing, Multi-layer packing, Unpacking and arrangement of big items, Dismantling and reassembly of basic furniture)",
    76: "commission",
    77: "informed partner that in lbr we can load the items whose weight is not more that 50kg of each and total 750kg",
    78: "Suspend",
    79: "Sir in micro shifting there will be distance of 10 kilometres and in other packege was 20 kilometres sir",
    80: "feed back",
    81: "Sir as of now we are giving the service on 14 cities sir Ahmedabad , Bangalore , Coimbatore , Delhi , Indore , Hyderabad , Jaipur , Lucknow , Mumbai , Nagpur , Chennai , Surat , Pune , Kolkata",
    82: "damage",
    83: "Inform the customer that we cannot provide specific charges for this service. If they wish to avail of this service, they can add it, and standard charges will be included in the total amount.",
    84: "Changes in Order Requirement - Require Add-on Services",
    85: "please dail this number 02244104444 after dialing press 1 your call has been connect to booking team , booking team will help you about your query"
};